---
abstract: 'Error/exception handling in an OO-ish way'
author:
  - 'Shlomi Fish ( http://www.shlomifish.org/ )'
build_requires: {}
configure_requires:
  Module::Build: 0.39
dynamic_config: 1
generated_by: 'Module::Build version 0.3901, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Error
provides:
  Error:
    file: lib/Error.pm
    version: 0.17020
  Error::Simple:
    file: lib/Error.pm
    version: 0.17020
  Error::WarnDie:
    file: lib/Error.pm
    version: 0
  Error::subs:
    file: lib/Error.pm
    version: 0
requires:
  Scalar::Util: 0
  perl: v5.6.0
  warnings: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.17020
